const translations = {
  en: {
    nav_about: "About",
    nav_impact: "Impact",
    nav_work: "Work",
    nav_publications: "Publications",
    nav_speaking: "Speaking",
    nav_contact: "Contact",
    hero_eyebrow: "Higher Education • Strategy • Lifelong Learning",
    hero_title: "Building the next generation of flexible, global, and human-centered learning ecosystems.",
    hero_lead: "I work at the intersection of higher education strategy, digital transformation, global engagement, and workforce-aligned lifelong learning.",
    hero_cta1: "Connect",
    hero_cta2: "Download resume",
    about_eyebrow: "Executive profile",
    about_title: "Higher education leader focused on institutional transformation and future-ready learning.",
    about_p1: "Dr. Mario F. Herane is a senior higher education executive with experience leading enterprise strategy, global affairs, digital transformation, enrollment growth, academic portfolio development, and institutional innovation across the U.S. and Latin America.",
    about_p2: "His work connects strategy with execution: building programs, partnerships, digital infrastructure, and learning pathways that help institutions respond to changing learners, labor markets, and global opportunities.",
    impact_eyebrow: "Selected impact",
    impact_title: "A record of strategy translated into measurable institutional results.",
    metric_1: "Institutional budget leadership experience",
    metric_2: "Online undergraduate and graduate students served",
    metric_3: "Undergraduate programs designed and launched",
    metric_4: "Graduate programs designed and launched",
    metric_5: "Annual continuing education portfolio revenue",
    metric_6: "Annual enrollment growth through market strategy",
    work_eyebrow: "Leadership platform",
    work_title: "Strategy, product, partnerships, and transformation as one integrated agenda.",
    work_card1_t: "Content & Product Strategy",
    work_card1_p: "Designing degree, certificate, and executive education portfolios aligned with workforce demand and institutional mission.",
    work_card2_t: "Digital Transformation",
    work_card2_p: "Scaling LMS, CRM, ERP, analytics, AI, and data governance capabilities to improve performance and student experience.",
    work_card3_t: "Global Affairs",
    work_card3_p: "Building international partnerships, cross-border pathways, and collaborations across the Americas and Europe.",
    work_card4_t: "Growth & Enrollment",
    work_card4_p: "Connecting market intelligence, segmentation, branding, recruitment, and student-centered enrollment management.",
    pub_eyebrow: "Publications, notes & public thinking",
    pub_title: "Ideas on higher education, technology, innovation, and lifelong learning.",
    pub_academic: "Academic publications",
    pub_thought: "Articles & notes",
    pub1_p: "A chapter connecting design thinking, entrepreneurship, youth empowerment, and social innovation in higher education.",
    pub2_p: "Early scientific publication on synthesis, structural characterization, and adsorption applications.",
    note1_p: "On the governance and ethical responsibilities of adopting AI in education.",
    note2_p: "On personalized pathways and lifelong learning as a strategic direction for universities.",
    note3_p: "On immersive technologies and their role in future learning experiences.",
    note4_p: "A public reflection on the need to keep human connection at the center of digital learning.",
    speak_eyebrow: "Speaking & advisory",
    speak_title: "Topics for panels, conferences, workshops, and institutional strategy sessions.",
    topic1_t: "Higher Education at a Crossroads",
    topic1_p: "Why lifelong learning requires a new university model.",
    topic2_t: "From Degrees to Dynamic Pathways",
    topic2_p: "Building stackable, skills-based, and personalized learning systems.",
    topic3_t: "AI, Ethics, and Institutional Transformation",
    topic3_p: "How universities can adopt AI responsibly and strategically.",
    topic4_t: "The Silver Economy and Workforce Development",
    topic4_p: "Learning systems for longer careers, productivity, and demographic change.",
    cred_eyebrow: "Education & credentials",
    cred_title: "A multidisciplinary academic foundation.",
    contact_eyebrow: "Contact",
    contact_title: "Let’s connect.",
    contact_p: "For speaking, advisory, partnerships, or strategic conversations:",
    footer: "All rights reserved."
    cert_eyebrow: "Certifications & Professional Development",
    cert_title: "Continuous learning as a professional commitment.",
    cert_intro: "Executive education and professional development in leadership, innovation, digital transformation, and institutional strategy.",
  },
  es: {
    nav_about: "Perfil",
    nav_impact: "Impacto",
    nav_work: "Trabajo",
    nav_publications: "Publicaciones",
    nav_speaking: "Charlas",
    nav_contact: "Contacto",
    hero_eyebrow: "Educación Superior • Estrategia • Aprendizaje Permanente",
    hero_title: "Construyendo la próxima generación de ecosistemas de aprendizaje flexibles, globales y centrados en las personas.",
    hero_lead: "Trabajo en la intersección entre estrategia en educación superior, transformación digital, vinculación global y aprendizaje permanente alineado al mundo laboral.",
    hero_cta1: "Conversemos",
    hero_cta2: "Descargar CV",
    about_eyebrow: "Perfil ejecutivo",
    about_title: "Líder en educación superior enfocado en transformación institucional y aprendizaje para el futuro.",
    about_p1: "El Dr. Mario F. Herane es un ejecutivo senior de educación superior con experiencia liderando estrategia institucional, asuntos globales, transformación digital, crecimiento de matrícula, desarrollo de portafolio académico e innovación institucional en Estados Unidos y América Latina.",
    about_p2: "Su trabajo conecta estrategia con ejecución: desarrollo de programas, alianzas, infraestructura digital y rutas de aprendizaje que permiten a las instituciones responder a nuevos estudiantes, mercados laborales y oportunidades globales.",
    impact_eyebrow: "Impacto seleccionado",
    impact_title: "Una trayectoria de estrategia convertida en resultados institucionales medibles.",
    metric_1: "Experiencia liderando presupuestos institucionales",
    metric_2: "Estudiantes online de pregrado y postgrado atendidos",
    metric_3: "Programas de pregrado diseñados y lanzados",
    metric_4: "Programas de postgrado diseñados y lanzados",
    metric_5: "Ingresos anuales de portafolio de educación continua",
    metric_6: "Crecimiento anual de matrícula vía estrategia de mercado",
    work_eyebrow: "Plataforma de liderazgo",
    work_title: "Estrategia, producto, alianzas y transformación como una agenda integrada.",
    work_card1_t: "Estrategia de contenido y producto",
    work_card1_p: "Diseño de portafolios de carreras, certificados y educación ejecutiva alineados con demanda laboral y misión institucional.",
    work_card2_t: "Transformación digital",
    work_card2_p: "Escalamiento de LMS, CRM, ERP, analítica, IA y gobierno de datos para mejorar desempeño y experiencia estudiantil.",
    work_card3_t: "Asuntos globales",
    work_card3_p: "Construcción de alianzas internacionales, rutas transfronterizas y colaboraciones en América y Europa.",
    work_card4_t: "Crecimiento y admisión",
    work_card4_p: "Conexión entre inteligencia de mercado, segmentación, marca, reclutamiento y gestión de matrícula centrada en el estudiante.",
    pub_eyebrow: "Publicaciones, notas y pensamiento público",
    pub_title: "Ideas sobre educación superior, tecnología, innovación y aprendizaje permanente.",
    pub_academic: "Publicaciones académicas",
    pub_thought: "Artículos y notas",
    pub1_p: "Capítulo que conecta design thinking, emprendimiento, empoderamiento juvenil e innovación social en educación superior.",
    pub2_p: "Publicación científica inicial sobre síntesis, caracterización estructural y aplicaciones de adsorción.",
    note1_p: "Sobre la gobernanza y las responsabilidades éticas de adoptar IA en educación.",
    note2_p: "Sobre rutas personalizadas y aprendizaje permanente como dirección estratégica para las universidades.",
    note3_p: "Sobre tecnologías inmersivas y su rol en futuras experiencias de aprendizaje.",
    note4_p: "Reflexión pública sobre la necesidad de mantener la conexión humana al centro del aprendizaje digital.",
    speak_eyebrow: "Charlas y asesoría",
    speak_title: "Temas para paneles, conferencias, talleres y sesiones de estrategia institucional.",
    topic1_t: "Educación superior en una encrucijada",
    topic1_p: "Por qué el aprendizaje permanente exige un nuevo modelo universitario.",
    topic2_t: "De grados a rutas dinámicas",
    topic2_p: "Construcción de sistemas apilables, personalizados y basados en habilidades.",
    topic3_t: "IA, ética y transformación institucional",
    topic3_p: "Cómo las universidades pueden adoptar IA de forma responsable y estratégica.",
    topic4_t: "Silver Economy y desarrollo laboral",
    topic4_p: "Sistemas de aprendizaje para carreras más largas, productividad y cambio demográfico.",
    cred_eyebrow: "Educación y credenciales",
    cred_title: "Una base académica multidisciplinaria.",
    contact_eyebrow: "Contacto",
    contact_title: "Conversemos.",
    contact_p: "Para charlas, asesorías, alianzas o conversaciones estratégicas:",
    footer: "Todos los derechos reservados."
    cert_eyebrow: "Certificaciones y Desarrollo Profesional",
    cert_title: "El aprendizaje continuo como compromiso profesional.",
    cert_intro: "Formación ejecutiva y desarrollo profesional en liderazgo, innovación, transformación digital y estrategia institucional.",
  }
};

function setLanguage(lang) {
  document.documentElement.lang = lang;
  localStorage.setItem("siteLanguage", lang);
  document.querySelectorAll("[data-i18n]").forEach((el) => {
    const key = el.getAttribute("data-i18n");
    if (translations[lang][key]) {
      el.textContent = translations[lang][key];
    }
  });
}

function toggleMenu() {
  document.getElementById("navLinks").classList.toggle("open");
}

document.getElementById("year").textContent = new Date().getFullYear();
setLanguage(localStorage.getItem("siteLanguage") || "en");
